# Generated by Django 4.1.2 on 2022-10-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.PositiveIntegerField()),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, default='product/default.png', null=True, upload_to='product/')),
            ],
        ),
    ]
